/**
 * samplePages.ts — pre-loaded demo content shown when the app first opens.
 *
 * ─── PURPOSE ──────────────────────────────────────────────────────────────────
 *
 * Real applications load pages from a database (see `prisma/seed.ts` for the
 * database equivalent). In the browser-only mode (no backend), these static
 * objects serve as the initial state so the app feels populated on first visit.
 *
 * ─── HOW TO ADD A NEW SAMPLE PAGE ─────────────────────────────────────────────
 *
 * 1. Add a new object to this array following the `Page` type shape.
 * 2. Give it a unique `id` string (used as the tree leaf's pageId).
 * 3. Add a corresponding entry to `initialTreeRoot` in Workspace.tsx so it
 *    appears in the sidebar file explorer.
 *
 * ─── BLOCK ID UNIQUENESS ──────────────────────────────────────────────────────
 *
 * Block `id` values must be unique across ALL pages (they are used as DnD
 * sortable item keys). Prefixing with the page name is a simple convention to
 * avoid collisions in this static data (e.g. 'intro', 'link-docs').
 *
 * In production, ids are generated by `crypto.randomUUID()` in `createBlock()`.
 *
 * ─── IMPROVEMENT IDEAS ────────────────────────────────────────────────────────
 *   - Load sample pages from a local JSON file for easier editing without
 *     touching TypeScript code.
 *   - Add more topic pages (e.g. "CSS Grid", "Git Workflow", "Docker Basics").
 *   - Show a "Welcome" page on first visit that explains how to use the app.
 */

import type { Page } from '@/components/MainContent';

export const samplePages: Page[] = [
  // ─── Page 1: React Hooks ──────────────────────────────────────────────────
  {
    id: 'react-hooks',
    title: 'React Hooks',
    blocks: [
      {
        id: 'intro',
        type: 'text',
        content:
          '<h2>What are React Hooks?</h2><p>React Hooks allow you to use <strong>state</strong> and other React features in <em>functional components</em> without writing a class.</p><p>They were introduced in React 16.8 and have become the standard way to manage component logic.</p>',
        colSpan: 2,
      },
      {
        // Half-width checklist — sits beside the link block in a 2-column row
        id: 'agenda-checklist',
        type: 'agenda',
        content: {
          title: 'Topics to cover',
          items: [
            { id: 'a1', text: 'useState — local component state', checked: true },
            { id: 'a2', text: 'useEffect — side effects & subscriptions', checked: true },
            { id: 'a3', text: 'useContext — consume React context', checked: false },
            { id: 'a4', text: 'useRef — mutable refs without re-render', checked: false },
            { id: 'a5', text: 'useMemo & useCallback — performance optimisation', checked: false },
          ],
        },
        colSpan: 1,
      },
      {
        // Half-width link — shares the row with the checklist above
        id: 'link-docs',
        type: 'link',
        content: {
          url: 'https://react.dev/reference/react',
          label: 'React Hooks Reference',
        },
        colSpan: 1,
      },
      {
        // Full-width code block demonstrating useState + useEffect together
        id: 'code-example',
        type: 'code',
        content: {
          code: `import React, { useState, useEffect } from "react";

function Counter() {
  const [count, setCount] = useState(0);

  useEffect(() => {
    document.title = \`Count: \${count}\`;
  }, [count]);

  return (
    <button onClick={() => setCount(c => c + 1)}>
      Count: {count}
    </button>
  );
}`,
          language: 'javascript',
        },
        colSpan: 2,
      },
      {
        // Reference table of all common hooks
        id: 'table-example',
        type: 'table',
        content: {
          headers: ['Hook', 'Purpose', 'Returns'],
          rows: [
            ['useState', 'Manage local state', '[state, setter]'],
            ['useEffect', 'Side effects', 'void'],
            ['useContext', 'Read context value', 'context value'],
            ['useRef', 'Mutable ref object', '{ current }'],
            ['useMemo', 'Memoize a value', 'memoized value'],
          ],
        },
        colSpan: 2,
      },
    ],
  },

  // ─── Page 2: TypeScript Tips ──────────────────────────────────────────────
  {
    id: 'typescript-tips',
    title: 'TypeScript Tips',
    blocks: [
      {
        id: 'ts-intro',
        type: 'text',
        content:
          '<h2>TypeScript Best Practices</h2><p>TypeScript adds <strong>static typing</strong> to JavaScript, catching errors at compile-time rather than runtime.</p><blockquote><p>Type safety is not a constraint — it\'s a superpower.</p></blockquote>',
        colSpan: 2,
      },
      {
        // Half-width image — TypeScript logo
        id: 'ts-image',
        type: 'image',
        content: {
          url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/512px-Typescript_logo_2020.svg.png',
          alt: 'TypeScript logo',
          caption: 'TypeScript — JavaScript with syntax for types',
        },
        colSpan: 1,
      },
      {
        // Half-width checklist — shares the row with the logo
        id: 'ts-agenda',
        type: 'agenda',
        content: {
          title: 'Must-know patterns',
          items: [
            { id: 'ts1', text: 'Use strict mode in tsconfig', checked: true },
            { id: 'ts2', text: 'Prefer interfaces over type aliases for objects', checked: false },
            { id: 'ts3', text: 'Use const assertions for literal types', checked: false },
            { id: 'ts4', text: 'Leverage utility types: Partial, Required, Pick', checked: false },
          ],
        },
        colSpan: 1,
      },
      {
        // Class diagram rendered by Mermaid.js showing TypeScript class inheritance
        id: 'ts-diagram',
        type: 'diagram',
        content: {
          code: `classDiagram
    class Animal {
        +String name
        +int age
        +speak() void
    }
    class Dog {
        +fetch() void
    }
    class Cat {
        +purr() void
    }
    Animal <|-- Dog
    Animal <|-- Cat`,
        },
        colSpan: 2,
      },
    ],
  },
];
